#!/bin/bash
cd /root/.openclaw/workspace/crypto-trend-trader
python backtest/run_backtest.py download \
    --timeframes 5m 15m 30m 1h \
    --start 2025-07-01 \
    --end 2026-04-21 \
    --symbols \
    PIPPIN/USDT:USDT ONT/USDT:USDT STABLE/USDT:USDT XRP/USDT:USDT NOT/USDT:USDT \
    ADA/USDT:USDT AVAX/USDT:USDT DOT/USDT:USDT TRX/USDT:USDT PEPE/USDT:USDT \
    MOODENG/USDT:USDT TRUMP/USDT:USDT RESOLV/USDT:USDT GALA/USDT:USDT ZIL/USDT:USDT \
    MEME/USDT:USDT ALGO/USDT:USDT BOME/USDT:USDT PUMP/USDT:USDT SAHARA/USDT:USDT \
    PENGU/USDT:USDT HUMA/USDT:USDT PEOPLE/USDT:USDT DOOD/USDT:USDT ORDER/USDT:USDT \
    ANIME/USDT:USDT ATH/USDT:USDT \
    >> backtest_r26_download.log 2>&1