#!/bin/bash
python backtest/run_backtest.py download \
    --timeframes 5m 15m 30m 1h \
    --start 2026-01-01 \
    --end 2026-04-06 \
    --symbols \
    SATS/USDT:USDT PEPE/USDT:USDT SHIB/USDT:USDT BONK/USDT:USDT FLOKI/USDT:USDT \
    RLS/USDT:USDT NEIRO/USDT:USDT PUMP/USDT:USDT DOGE/USDT:USDT GALA/USDT:USDT \
    PIPPIN/USDT:USDT TURBO/USDT:USDT HMSTR/USDT:USDT PENGU/USDT:USDT BOME/USDT:USDT \
    NOT/USDT:USDT MEME/USDT:USDT CORE/USDT:USDT MMT/USDT:USDT MEW/USDT:USDT \
    KAT/USDT:USDT BASED/USDT:USDT MON/USDT:USDT ONT/USDT:USDT FOGO/USDT:USDT \
    XPL/USDT:USDT SAHARA/USDT:USDT PEOPLE/USDT:USDT SPACE/USDT:USDT NIGHT/USDT:USDT \
    DOOD/USDT:USDT RSR/USDT:USDT ZIL/USDT:USDT ORDER/USDT:USDT IOST/USDT:USDT \
    TRIA/USDT:USDT MOODENG/USDT:USDT ROBO/USDT:USDT ADA/USDT:USDT APR/USDT:USDT \
    ALGO/USDT:USDT BSB/USDT:USDT ANIME/USDT:USDT HUMA/USDT:USDT RESOLV/USDT:USDT \
    XRP/USDT:USDT ATH/USDT:USDT ZK/USDT:USDT BEAT/USDT:USDT STABLE/USDT:USDT \
    AVAX/USDT:USDT LINK/USDT:USDT DOT/USDT:USDT TRX/USDT:USDT TRUMP/USDT:USDT
