#!/bin/bash
cd /root/.openclaw/workspace/crypto-trend-trader
python backtest/run_backtest.py download \
    --timeframes 5m 15m 30m 1h \
    --start 2025-07-01 \
    --end 2026-04-21 \
    --symbols \
    SATS/USDT:USDT SHIB/USDT:USDT BONK/USDT:USDT NEIRO/USDT:USDT FLOKI/USDT:USDT \
    HMSTR/USDT:USDT BASED/USDT:USDT TURBO/USDT:USDT MEW/USDT:USDT BLUR/USDT:USDT \
    RAVE/USDT:USDT BIO/USDT:USDT SPACE/USDT:USDT CHZ/USDT:USDT GPS/USDT:USDT \
    OFC/USDT:USDT SENT/USDT:USDT KAT/USDT:USDT MON/USDT:USDT SPK/USDT:USDT \
    PIEVERSE/USDT:USDT MERL/USDT:USDT ROBO/USDT:USDT ENJ/USDT:USDT CHIP/USDT:USDT \
    BSB/USDT:USDT W/USDT:USDT WLFI/USDT:USDT IOST/USDT:USDT XPL/USDT:USDT \
    PLUME/USDT:USDT RLS/USDT:USDT \
    >> backtest_r27_download.log 2>&1